name: Deploy Javadoc
description: "Automatically  generate your Javadoc from your maven project and deploy it with GitHub Page on javadoc branch."
branding:
  icon: "book-open"
  color: "white"

inputs:

  # Required inputs
  java-version: # version of java
    description: "Java version inside your project"
    required: true
    default: "17"
    type: string
  GITHUB_TOKEN: # GitHub Token
    description: "The GitHub token the GitHub repository"
    required: true
  javadoc-branch: # branch where the javadoc is hosted
    description: "Branch where the javadoc is hosted"
    required: true
    default: javadoc
    type: string
  target-folder: # target folder for the javadoc contents
    description: "Directory where the javadoc contents should be stored"
    required: true
    default: .
    type: string

  # Optional inputs
  java-distribution: # distribution of java
    description: "Java distribution inside your project"
    required: false
    default: "adopt"
  project:
    description: "Maven or Gradle project"
    required: false
    default: maven
    type: choice
    options:
      - maven
      - gradle

  # Development and testing inputs
  without-deploy: # deploy the javadoc to the GitHub Page, is used for development testing with nektos/act
    description: "Enable or disable deploy of the javadoc to the GitHub Page"
    required: false
    default: "false"
    type: boolean
  without-checkout: # checkout the javadoc branch, is used for development testing with nektos/act
    description: "Enable or disable the checkout"
    required: false
    default: "false"
    type: boolean

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      if: inputs.without-checkout == 'false'
      with:
        fetch-depth: 0

    - uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        cache: ${{ inputs.project }}

    - name: Generate Javadoc with Maven
      if: inputs.project == 'maven'
      run: mvn javadoc:javadoc
      shell: bash

    - name: Generate Javadoc with Gradle
      if: inputs.project == 'gradle'
      run: gradle javadoc
      shell: bash

    - name: Deploy to GitHub Page 🚀 with Maven
      if: ${{ inputs.without-deploy == 'false' && inputs.project == 'maven' }}
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        branch: ${{ inputs.javadoc-branch }}
        clean: true
        folder: target/site/apidocs
        target-folder: ${{ inputs.target-folder }}

    - name: Deploy to GitHub Page 🚀 with Gradle
      if: ${{ inputs.without-deploy == 'false' && inputs.project == 'gradle' }}
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        branch: ${{ inputs.javadoc-branch }}
        clean: true
        folder: build/docs/javadoc
        target-folder: ${{ inputs.target-folder }}
