name: Deploy Javadoc
description: 'Automatically  generate your Javadoc from your maven project and deploy it with GitHub Page on javadoc branch.'
branding:
  icon: 'book-open'
  color: 'white'
inputs:
  java-version:  # version of java
    description: 'Java version inside your project'
    required: true
    default: '17'
  GITHUB_TOKEN: # GitHub Token
    description: 'The GitHub token the GitHub repository'
    required: true
  javadoc-branch: # branch where the javadoc is hosted
    description: 'Branch where the javadoc is hosted'
    required: true
    default: javadoc
  target-folder: # target folder for the javadoc contents
    description: 'Directory where the javadoc contents should be stored'
    required: true
    default: .
 
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
    with:
      fetch-depth: 0
  - uses: actions/setup-java@v3
    with:
      java-version: ${{ inputs.java-version }}
      distribution: 'adopt'
  - name: Generate Javadoc
    run: mvn org.apache.maven.plugins:maven-javadoc-plugin:3.4.0:aggregate
    shell: bash
  - name: Deploy 🚀
    uses: JamesIves/github-pages-deploy-action@v4.4.1
    with:
      token: ${{ inputs.GITHUB_TOKEN }}
      branch: ${{ inputs.javadoc-branch }}
      clean: true
      folder: target/site/apidocs
      target-folder: ${{ inputs.target-folder }} 
