name: Test Actions locally

on: [workflow_dispatch]

jobs:
  check-pom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: GuillaumeFalourd/assert-command-line-output@v2.3
        with:
          command_line: cat pom.xml
          contains: JAVAVERSION

  test-for-github-workflow: # Test the action with the GitHub workflow
    needs: check-pom
    continue-on-error: true
    strategy:
      matrix:
        java: [17]
        java-distribution: [temurin]
        os: [ubuntu-latest]
        project: [maven]
        exclude:
          - java: 8
            java-distribution: microsoft
          - java: 18
            java-distribution: microsoft
          - java: 19
            java-distribution: microsoft
          - java: 19
            project: gradle
            os: windows-latest
    runs-on: ${{ matrix.os }}

    name: Test Java ${{ matrix.java }} ${{ matrix.java-distribution }} ${{ matrix.project }} - ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Replace string in file
        uses: MathieuSoysal/replace-string-in-file@v1.1.0
        with:
          file: pom.xml
          old-string: JAVAVERSION
          new-string: ${{ matrix.java }}

      - uses: ./ # Uses an action in the root directory
        if: ${{ matrix.project == 'maven' }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc-test
          java-version: ${{ matrix.java }}
          target-folder: javadoc
          project: ${{ matrix.project }}
          java-distribution: ${{ matrix.java-distribution }}
          without-deploy: true
          without-checkout: true

      - uses: GuillaumeFalourd/assert-command-line-output@v2.3
        if: ${{ matrix.project == 'maven' }}
        with:
          command_line: cat target/site/apidocs/index.html
          contains: javadoc
